# Generated by Django 5.2.17 on 2026-08-31 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talukas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_ACTIVATED', 'User activated'), ('USER_DELETED', 'User deleted'), ('TAHSILDAR_CREATED', 'Tahsildar created'), ('TAHSILDAR_UPDATED', 'Tahsildar updated'), ('TAHSILDAR_DEACTIVATED', 'Tahsildar deactivated'), ('RECORD_CREATED', 'Record created'), ('RECORD_UPDATED', 'Record updated'), ('RECORD_DEACTIVATED', 'Record deactivated'), ('PASSWORD_RESET', 'Password reset'), ('ROLE_CHANGED', 'Role changed'), ('TALUKA_CHANGED', 'Taluka changed')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='talukas.taluka')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['taluka', 'timestamp'], name='audit_audit_taluka__508065_idx')],
            },
        ),
    ]
