# Generated by Django 5.2.17 on 2026-08-31 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talukas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='talukas.taluka')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['taluka__code', 'record_number'],
                'indexes': [models.Index(fields=['taluka', 'is_active'], name='records_rec_taluka__15fae3_idx'), models.Index(fields=['taluka', 'status'], name='records_rec_taluka__2dd4ef_idx'), models.Index(fields=['created_at'], name='records_rec_created_85482c_idx')],
            },
        ),
    ]
